# Generated by Django 5.2.7 on 2025-10-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_seotoolkit', '0009_remove_is_verified_field'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="The SEO meta description that will replace the page's default meta description", max_length=320)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this description is currently active. Only one description can be active per page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(help_text='The page this SEO meta description applies to', on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta_descriptions', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'is_active'], name='wagtail_seo_page_id_dafea9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEOTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The SEO title that will replace the page's default title tag", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this title is currently active. Only one title can be active per page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(help_text='The page this SEO title applies to', on_delete=django.db.models.deletion.CASCADE, related_name='seo_titles', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'is_active'], name='wagtail_seo_page_id_a4e113_idx')],
            },
        ),
    ]
