# Generated by Django 5.2.7 on 2025-11-06 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_seotoolkit", "0010_seometadatatemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "instance_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription License",
                "verbose_name_plural": "Subscription Licenses",
            },
        ),
    ]
