# Generated by Django 5.2.7 on 2025-11-06 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_seotoolkit", "0011_subscriptionlicense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionlicense",
            name="email",
        ),
    ]
