# Generated by Django 5.2.8 on 2025-11-18 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_seotoolkit', '0013_add_placeholder_unprocessed_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_change', models.IntegerField(help_text='Change in overall score (can be negative)')),
                ('new_issues_count', models.IntegerField(default=0, help_text='Total number of new issues in current audit')),
                ('fixed_issues_count', models.IntegerField(default=0, help_text='Total number of issues fixed since previous audit')),
                ('new_issues_old_pages_count', models.IntegerField(default=0, help_text='New issues on pages that existed in previous audit')),
                ('new_issues_new_pages_count', models.IntegerField(default=0, help_text='New issues on pages created after previous audit')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent for this report')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email notification was sent', null=True)),
                ('current_audit', models.ForeignKey(help_text='The more recent audit run', on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_current', to='wagtail_seotoolkit.seoauditrun')),
                ('previous_audit', models.ForeignKey(help_text='The older audit run being compared against', on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_previous', to='wagtail_seotoolkit.seoauditrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
