# Generated by Django 5.2.8 on 2025-12-01 22:11
# Manually modified to handle ForeignKey to BooleanField conversion

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtail_seotoolkit", "0015_jsonld_schema_models"),
    ]

    operations = [
        # First, remove the old ForeignKey use_template field (must be done separately)
        migrations.RemoveField(
            model_name="pagejsonldoverride",
            name="use_template",
        ),
        # Remove the old schema_fields and schema_type fields
        migrations.RemoveField(
            model_name="jsonldschematemplate",
            name="schema_fields",
        ),
        migrations.RemoveField(
            model_name="jsonldschematemplate",
            name="schema_type",
        ),
        migrations.RemoveField(
            model_name="pagejsonldoverride",
            name="schema_fields",
        ),
        migrations.RemoveField(
            model_name="pagejsonldoverride",
            name="schema_type",
        ),
        # Now add the new boolean use_template field
        migrations.AddField(
            model_name="pagejsonldoverride",
            name="use_template",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, merge with page type template. If disabled, use only these schemas.",
            ),
        ),
        # Add the new schemas StreamField
        migrations.AddField(
            model_name="jsonldschematemplate",
            name="schemas",
            field=wagtail.fields.StreamField(
                [
                    ("article", 27),
                    ("blog_posting", 31),
                    ("news_article", 35),
                    ("report", 42),
                    ("scholarly_article", 49),
                    ("faq_page", 54),
                    ("web_page", 58),
                    ("organization", 74),
                    ("person", 81),
                    ("place", 87),
                    ("monetary_grant", 94),
                    ("project", 100),
                    ("event", 105),
                    ("product", 109),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Article headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Article description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 date or {first_published_at} placeholder",
                            "label": "Date Published",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 date or {last_published_at} placeholder",
                            "label": "Date Modified",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Person name or {field} placeholder (e.g., {author_name})",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Profile URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {author_image})",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Job title or {field} placeholder",
                            "label": "Job Title",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {}),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Links to social media profiles or other URLs",
                            "label": "Social/Profile URLs",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 4),
                                ("url", 5),
                                ("image", 6),
                                ("job_title", 7),
                                ("same_as", 9),
                            ]
                        ],
                        {"label": "Author", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization name or {site_name} placeholder",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Organization URL", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Logo URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Publisher", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {header_image})",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image width in pixels", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image height in pixels", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption or {field} placeholder",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"label": "Main Image", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "CSS selectors for speakable content (e.g., .article-body, h1)",
                            "label": "CSS Selectors",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "XPath expressions for speakable content",
                            "label": "XPath Expressions",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("css_selector", 20), ("xpath", 21)]],
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Schema.org property (e.g., wordCount, inLanguage)",
                            "label": "Property Name",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static value or {field} placeholder (e.g., {title}, {first_published_at})",
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("property_name", 23), ("value", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"label": "Additional Properties", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("description", 1),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Blog post headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Post description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Word count or {word_count} placeholder",
                            "label": "Word Count",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 28),
                                ("description", 29),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("word_count", 30),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "News headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "News description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Location and date line (e.g., 'NEW YORK, Dec 1')",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 32),
                                ("description", 33),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("dateline", 34),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Report title or {title} placeholder",
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Report description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "URL to the media file or {field} placeholder",
                            "label": "Content URL",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "MIME type (e.g., application/pdf, video/mp4)",
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Media name or {field} placeholder",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("content_url", 38), ("encoding_format", 39), ("name", 40)]],
                        {
                            "help_text": "Link to downloadable PDF version",
                            "label": "PDF/Document",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 36),
                                ("description", 37),
                                ("date_published", 2),
                                ("author", 10),
                                ("publisher", 14),
                                ("encoding", 41),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Article title or {title} placeholder",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Abstract or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Date Published", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 4),
                                ("url", 5),
                                ("image", 6),
                                ("job_title", 7),
                                ("same_as", 9),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.ListBlock",
                        (46,),
                        {
                            "help_text": "Add multiple authors",
                            "label": "Authors",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("content_url", 38), ("encoding_format", 39), ("name", 40)]],
                        {"label": "PDF/Document", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 43),
                                ("description", 44),
                                ("date_published", 45),
                                ("author", 47),
                                ("publisher", 14),
                                ("encoding", 48),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Question text or {field} placeholder",
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Answer text or {field} placeholder",
                            "required": True,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 50), ("answer", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {
                            "help_text": "Add question/answer pairs",
                            "label": "FAQ Items",
                            "required": True,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("main_entity", 53), ("additional_properties", 26)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Page name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Page description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Date Modified", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 55),
                                ("description", 56),
                                ("date_published", 45),
                                ("date_modified", 57),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    60: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Organization description", "required": False},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Street Address", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "City", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "State/Region", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Postal Code", "required": False},
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Country", "required": False},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("street_address", 61),
                                ("address_locality", 62),
                                ("address_region", 63),
                                ("postal_code", 64),
                                ("address_country", 65),
                            ]
                        ],
                        {"required": False},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Phone number", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address", "required": False},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., customer service, sales, technical support",
                            "label": "Contact Type",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Languages supported (e.g., English, Spanish)",
                            "label": "Available Languages",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("telephone", 67),
                                ("email", 68),
                                ("contact_type", 69),
                                ("available_language", 70),
                            ]
                        ],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.ListBlock",
                        (71,),
                        {"label": "Contact Points", "required": False},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Links to social media profiles",
                            "label": "Social/Profile URLs",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 59),
                                ("description", 60),
                                ("url", 12),
                                ("logo", 13),
                                ("address", 66),
                                ("contact_point", 72),
                                ("same_as", 73),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Person name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    76: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Biography or description", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Job Title", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"label": "Photo", "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Works For", "required": False},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {"label": "Social/Profile URLs", "required": False},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 75),
                                ("description", 76),
                                ("job_title", 77),
                                ("image", 78),
                                ("works_for", 79),
                                ("same_as", 80),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Place name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    83: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    84: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Latitude", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Longitude", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 82),
                                ("description", 83),
                                ("address", 66),
                                ("geo_latitude", 84),
                                ("geo_longitude", 85),
                                ("image", 86),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Grant name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Amount value or {field} placeholder",
                            "required": True,
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "USD",
                            "help_text": "Currency code (e.g., USD, EUR, GBP)",
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 89), ("currency", 90)]],
                        {"label": "Grant Amount", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Funder", "required": False},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project or item being funded",
                            "label": "Funded Item",
                            "required": False,
                        },
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 88),
                                ("description", 83),
                                ("amount", 91),
                                ("funder", 92),
                                ("funded_item", 93),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Start Date", "required": False},
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "End Date", "required": False},
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Place name or {field} placeholder",
                            "required": True,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 98),
                                ("address", 66),
                                ("geo_latitude", 84),
                                ("geo_longitude", 85),
                            ]
                        ],
                        {"required": False},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 95),
                                ("description", 83),
                                ("start_date", 96),
                                ("end_date", 97),
                                ("funder", 92),
                                ("location", 99),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 format or {field} placeholder",
                            "label": "Start Date/Time",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "End Date/Time", "required": False},
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"required": False},
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 101),
                                ("description", 83),
                                ("start_date", 102),
                                ("end_date", 103),
                                ("location", 99),
                                ("organizer", 104),
                                ("image", 86),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Product name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Brand name", "required": False},
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "SKU", "required": False},
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 106),
                                ("description", 83),
                                ("image", 86),
                                ("brand", 107),
                                ("sku", 108),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add schema types (BlogPosting, Article, etc.) and configure their fields.",
            ),
        ),
        migrations.AddField(
            model_name="pagejsonldoverride",
            name="schemas",
            field=wagtail.fields.StreamField(
                [
                    ("article", 27),
                    ("blog_posting", 31),
                    ("news_article", 35),
                    ("report", 42),
                    ("scholarly_article", 49),
                    ("faq_page", 54),
                    ("web_page", 58),
                    ("organization", 74),
                    ("person", 81),
                    ("place", 87),
                    ("monetary_grant", 94),
                    ("project", 100),
                    ("event", 105),
                    ("product", 109),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Article headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Article description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 date or {first_published_at} placeholder",
                            "label": "Date Published",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 date or {last_published_at} placeholder",
                            "label": "Date Modified",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Person name or {field} placeholder (e.g., {author_name})",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Profile URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {author_image})",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Job title or {field} placeholder",
                            "label": "Job Title",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {}),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Links to social media profiles or other URLs",
                            "label": "Social/Profile URLs",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 4),
                                ("url", 5),
                                ("image", 6),
                                ("job_title", 7),
                                ("same_as", 9),
                            ]
                        ],
                        {"label": "Author", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization name or {site_name} placeholder",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Organization URL", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Logo URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Publisher", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {header_image})",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image width in pixels", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image height in pixels", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption or {field} placeholder",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"label": "Main Image", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "CSS selectors for speakable content (e.g., .article-body, h1)",
                            "label": "CSS Selectors",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "XPath expressions for speakable content",
                            "label": "XPath Expressions",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("css_selector", 20), ("xpath", 21)]],
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Schema.org property (e.g., wordCount, inLanguage)",
                            "label": "Property Name",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static value or {field} placeholder (e.g., {title}, {first_published_at})",
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("property_name", 23), ("value", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"label": "Additional Properties", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("description", 1),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Blog post headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Post description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Word count or {word_count} placeholder",
                            "label": "Word Count",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 28),
                                ("description", 29),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("word_count", 30),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "News headline or {title} placeholder",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "News description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Location and date line (e.g., 'NEW YORK, Dec 1')",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 32),
                                ("description", 33),
                                ("date_published", 2),
                                ("date_modified", 3),
                                ("author", 10),
                                ("publisher", 14),
                                ("image", 19),
                                ("dateline", 34),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Report title or {title} placeholder",
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Report description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "URL to the media file or {field} placeholder",
                            "label": "Content URL",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "MIME type (e.g., application/pdf, video/mp4)",
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Media name or {field} placeholder",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("content_url", 38), ("encoding_format", 39), ("name", 40)]],
                        {
                            "help_text": "Link to downloadable PDF version",
                            "label": "PDF/Document",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 36),
                                ("description", 37),
                                ("date_published", 2),
                                ("author", 10),
                                ("publisher", 14),
                                ("encoding", 41),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Article title or {title} placeholder",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Abstract or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Date Published", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 4),
                                ("url", 5),
                                ("image", 6),
                                ("job_title", 7),
                                ("same_as", 9),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.ListBlock",
                        (46,),
                        {
                            "help_text": "Add multiple authors",
                            "label": "Authors",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("content_url", 38), ("encoding_format", 39), ("name", 40)]],
                        {"label": "PDF/Document", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 43),
                                ("description", 44),
                                ("date_published", 45),
                                ("author", 47),
                                ("publisher", 14),
                                ("encoding", 48),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Question text or {field} placeholder",
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Answer text or {field} placeholder",
                            "required": True,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 50), ("answer", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {
                            "help_text": "Add question/answer pairs",
                            "label": "FAQ Items",
                            "required": True,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("main_entity", 53), ("additional_properties", 26)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Page name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Page description or {search_description} placeholder",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Date Modified", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 55),
                                ("description", 56),
                                ("date_published", 45),
                                ("date_modified", 57),
                                ("speakable", 22),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    60: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Organization description", "required": False},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Street Address", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "City", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "State/Region", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Postal Code", "required": False},
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Country", "required": False},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("street_address", 61),
                                ("address_locality", 62),
                                ("address_region", 63),
                                ("postal_code", 64),
                                ("address_country", 65),
                            ]
                        ],
                        {"required": False},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Phone number", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address", "required": False},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., customer service, sales, technical support",
                            "label": "Contact Type",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Languages supported (e.g., English, Spanish)",
                            "label": "Available Languages",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("telephone", 67),
                                ("email", 68),
                                ("contact_type", 69),
                                ("available_language", 70),
                            ]
                        ],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.ListBlock",
                        (71,),
                        {"label": "Contact Points", "required": False},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Links to social media profiles",
                            "label": "Social/Profile URLs",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 59),
                                ("description", 60),
                                ("url", 12),
                                ("logo", 13),
                                ("address", 66),
                                ("contact_point", 72),
                                ("same_as", 73),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Person name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    76: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Biography or description", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Job Title", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"label": "Photo", "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Works For", "required": False},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {"label": "Social/Profile URLs", "required": False},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 75),
                                ("description", 76),
                                ("job_title", 77),
                                ("image", 78),
                                ("works_for", 79),
                                ("same_as", 80),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Place name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    83: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    84: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Latitude", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Longitude", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 15), ("width", 16), ("height", 17), ("caption", 18)]],
                        {"required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 82),
                                ("description", 83),
                                ("address", 66),
                                ("geo_latitude", 84),
                                ("geo_longitude", 85),
                                ("image", 86),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Grant name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Amount value or {field} placeholder",
                            "required": True,
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "USD",
                            "help_text": "Currency code (e.g., USD, EUR, GBP)",
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 89), ("currency", 90)]],
                        {"label": "Grant Amount", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"label": "Funder", "required": False},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project or item being funded",
                            "label": "Funded Item",
                            "required": False,
                        },
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 88),
                                ("description", 83),
                                ("amount", 91),
                                ("funder", 92),
                                ("funded_item", 93),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Start Date", "required": False},
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "End Date", "required": False},
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Place name or {field} placeholder",
                            "required": True,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 98),
                                ("address", 66),
                                ("geo_latitude", 84),
                                ("geo_longitude", 85),
                            ]
                        ],
                        {"required": False},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 95),
                                ("description", 83),
                                ("start_date", 96),
                                ("end_date", 97),
                                ("funder", 92),
                                ("location", 99),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "ISO 8601 format or {field} placeholder",
                            "label": "Start Date/Time",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "End Date/Time", "required": False},
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("url", 12), ("logo", 13)]],
                        {"required": False},
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 101),
                                ("description", 83),
                                ("start_date", 102),
                                ("end_date", 103),
                                ("location", 99),
                                ("organizer", 104),
                                ("image", 86),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Product name or {title} placeholder",
                            "required": True,
                        },
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Brand name", "required": False},
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "SKU", "required": False},
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 106),
                                ("description", 83),
                                ("image", 86),
                                ("brand", 107),
                                ("sku", 108),
                                ("additional_properties", 26),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add schema types and configure their fields. These override template values.",
            ),
        ),
        # Update content_type to OneToOneField
        migrations.AlterField(
            model_name="jsonldschematemplate",
            name="content_type",
            field=models.OneToOneField(
                blank=True,
                help_text="Select a page type. Leave blank for a default template for all page types.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jsonld_template",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="jsonldschematemplate",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this template (e.g., 'Blog Post Schemas')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitewidejsonldschema",
            name="schema_fields",
            field=wagtail.fields.StreamField(
                [
                    ("property", 2),
                    ("image", 7),
                    ("address", 13),
                    ("contact_point", 19),
                    ("person", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Schema.org property (e.g., wordCount, inLanguage)",
                            "label": "Property Name",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static value or {field} placeholder (e.g., {title}, {first_published_at})",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("property_name", 0), ("value", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {header_image})",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image width in pixels", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image height in pixels", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption or {field} placeholder",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 3), ("width", 4), ("height", 5), ("caption", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Street Address", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "City", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "State/Region", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Postal Code", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Country", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("street_address", 8),
                                ("address_locality", 9),
                                ("address_region", 10),
                                ("postal_code", 11),
                                ("address_country", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Phone number", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., customer service, sales, technical support",
                            "label": "Contact Type",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {}),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {
                            "help_text": "Languages supported (e.g., English, Spanish)",
                            "label": "Available Languages",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("telephone", 14),
                                ("email", 15),
                                ("contact_type", 16),
                                ("available_language", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Person name or {field} placeholder (e.g., {author_name})",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Profile URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {author_image})",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Job title or {field} placeholder",
                            "label": "Job Title",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {
                            "help_text": "Links to social media profiles or other URLs",
                            "label": "Social/Profile URLs",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 20),
                                ("url", 21),
                                ("image", 22),
                                ("job_title", 23),
                                ("same_as", 24),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Additional schema properties. Base name/url are auto-populated from Site settings.",
            ),
        ),
    ]
