# Generated by Django 5.2.8 on 2025-12-01 22:46
# Manually modified to handle data migration

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def delete_old_site_schemas(apps, schema_editor):
    """Delete old site-wide schemas before restructuring."""
    SiteWideJSONLDSchema = apps.get_model("wagtail_seotoolkit", "SiteWideJSONLDSchema")
    SiteWideJSONLDSchema.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_seotoolkit", "0017_add_recipe_schema_type"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        # First delete all existing site-wide schemas (data migration)
        migrations.RunPython(delete_old_site_schemas, migrations.RunPython.noop),
        # Remove unique_together constraint
        migrations.AlterUniqueTogether(
            name="sitewidejsonldschema",
            unique_together=set(),
        ),
        # Remove old fields first
        migrations.RemoveField(
            model_name="sitewidejsonldschema",
            name="schema_fields",
        ),
        migrations.RemoveField(
            model_name="sitewidejsonldschema",
            name="schema_type",
        ),
        # Add new schemas field
        migrations.AddField(
            model_name="sitewidejsonldschema",
            name="schemas",
            field=wagtail.fields.StreamField(
                [("organization", 21), ("website", 30), ("local_business", 45)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Organization description", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Logo URL", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Street Address", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "City", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "State/Region", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Postal Code", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Country", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("street_address", 2),
                                ("address_locality", 3),
                                ("address_region", 4),
                                ("postal_code", 5),
                                ("address_country", 6),
                            ]
                        ],
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Phone number", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., customer service, sales, technical support",
                            "label": "Contact Type",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {
                            "help_text": "Languages supported (e.g., English, Spanish)",
                            "label": "Available Languages",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("telephone", 8),
                                ("email", 9),
                                ("contact_type", 10),
                                ("available_language", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"label": "Contact Points", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {
                            "help_text": "Links to social media profiles (Facebook, Twitter, LinkedIn, etc.)",
                            "label": "Social Media URLs",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Year or date founded (e.g., 1990 or 1990-01-15)",
                            "label": "Founding Date",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Schema.org property (e.g., wordCount, inLanguage)",
                            "label": "Property Name",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static value or {field} placeholder (e.g., {title}, {first_published_at})",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("property_name", 17), ("value", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {"label": "Additional Properties", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("description", 0),
                                ("logo", 1),
                                ("address", 7),
                                ("contact_point", 14),
                                ("same_as", 15),
                                ("founding_date", 16),
                                ("additional_properties", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Website description", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization name or {site_name} placeholder",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Organization URL", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Logo URL or {field} placeholder",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 23), ("url", 24), ("logo", 25)]],
                        {
                            "help_text": "Organization that publishes this website",
                            "label": "Publisher",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add SearchAction for site search functionality",
                            "label": "Enable Search Action",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/search/?q={search_term_string}",
                            "help_text": "Search URL with {search_term_string} placeholder (e.g., /search/?q={search_term_string})",
                            "label": "Search URL Template",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary language code (e.g., en, en-US, de)",
                            "label": "Language",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("description", 22),
                                ("publisher", 26),
                                ("potential_action_search", 27),
                                ("search_url_template", 28),
                                ("in_language", 29),
                                ("additional_properties", 20),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Business description", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image URL or {field} placeholder (e.g., {header_image})",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image width in pixels", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Image height in pixels", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption or {field} placeholder",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 32), ("width", 33), ("height", 34), ("caption", 35)]],
                        {"label": "Business Image", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("street_address", 2),
                                ("address_locality", 3),
                                ("address_region", 4),
                                ("postal_code", 5),
                                ("address_country", 6),
                            ]
                        ],
                        {"label": "Business Address", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Business phone number", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Business email", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Price range indicator (e.g., $$, $$$, €€)",
                            "label": "Price Range",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {
                            "help_text": "Opening hours in schema.org format (e.g., Mo-Fr 09:00-17:00)",
                            "label": "Opening Hours",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Latitude", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {"label": "Longitude", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {"label": "Social Media URLs", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("description", 31),
                                ("image", 36),
                                ("address", 37),
                                ("telephone", 38),
                                ("email", 39),
                                ("price_range", 40),
                                ("opening_hours", 41),
                                ("geo_latitude", 42),
                                ("geo_longitude", 43),
                                ("same_as", 44),
                                ("additional_properties", 20),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add site-wide schemas (Organization, WebSite, LocalBusiness). Name and URL are auto-populated from Site settings.",
            ),
        ),
        # Update site field to OneToOneField
        migrations.AlterField(
            model_name="sitewidejsonldschema",
            name="site",
            field=models.OneToOneField(
                help_text="The Wagtail site this schema belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jsonld_schema",
                to="wagtailcore.site",
            ),
        ),
        migrations.AlterField(
            model_name="sitewidejsonldschema",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether site-wide schemas should be included on pages",
            ),
        ),
    ]
