# Generated by Django 5.2.8 on 2026-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_seotoolkit', '0021_alter_jsonldschematemplate_schemas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftseoaudit',
            name='check_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed check data for UI widgets (title, meta, images, links)'),
        ),
    ]
